# Generated by Django 4.0.4 on 2022-04-19 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=600)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('stock', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocklists', to='stocksbot_app.stocklist')),
            ],
        ),
    ]
